version: '2'
services:
  vas_tsh_prod:
    container_name: vas_tsh_prod
    build: .
    hostname: vasprod
    #command: --domain=vasprod --realm=vasprod
    ports:
      - "8093:8093"
      - "8091:8091"
      - "8080:8080"
      - "8070:8070"
      - "9000:9000"
      - "10000:80"
    volumes:
      - /var/www/html
    restart: always
    links:
      - db
    command: /home/run_startup_scripts.sh
    networks:
      local_connection:
        aliases:
          - vasprod
  vas_tsh_dev:
    container_name: vas_tsh_dev
    build: .
    hostname: vasdev
    build: .
    ports:
     - "8094:8093"
     - "8092:8091"
     - "8081:8080"
     - "8071:8070"
     - "9001:9000"
     - "10001:80"
    volumes:
     - /var/www/html
    restart: always
    links:
      - db
    command: /home/run_startup_scripts.sh
    networks:
      local_connection:
        aliases:
          - vasdev
  db:
    container_name: mysql
    image: mysql
    hostname: mysql
    ports: 
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=vasdb
      - MYSQL_USER=vasuser
      - MYSQL_PASSWORD=pass
    volumes_from:
      - vas_tsh_prod
    networks:
      local_connection:
        aliases:
          - mysql      
networks:
  local_connection:
